version: "3.9"
   
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
         
  web:
    build:
      context: backendAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links: 
      - db
      
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'